# Site settings
title: Wendy's Code Blog
email: gmfholley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog!  Please come in and make yourself at home!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gmfholley
github_username:  gmfholley

# Build settings
markdown: redcarpet
